ARTIST_WHITELIST = [
  "10 Years",
  "12 Stones",
  "3 Doors Down",
  "30 Seconds to Mars",
  "5 Seconds of Summer",
  "5'Nizza",
  "65daysofstatic",
  "7Б",
  "A Day to Remember",
  "ABBA",
  "AC/DC",
  "AFI",
  "ATB",
  "AURORA",
  "AWOLNATION",
  "AaRON",
  "Abel Korzeniowski",
  "Adam Gontier",
  "Adam Lambert",
  "Adam Levine",
  "Adele",
  "Adelitas Way",
  "Aerosmith",
  "Agnes Obel",
  "Akute",
  "Alai Oli",
  "Alex Band",
  "Alexandre Desplat",
  "Alexi Murdoch",
  "Alina Orlova",
  "Alizbar",
  "AlunaGeorge",
  "Amber Run",
  "Amiina",
  "Anberlin",
  "Andrea Bocelli",
  "Andrew Belle",
  "Ane Brun",
  "Anna Rose Carter",
  "AnnenMayKantereit",
  "Apocalyptica",
  "Aquilo",
  "Arcade Fire",
  "Archive",
  "Ashes Remain",
  "Ashram",
  "Asking Alexandria",
  "Athlete",
  "Audioslave",
  "Augustana",
  "Autoheart",
  "Autumn Rain Melancholy",
  "Avenged Sevenfold",
  "Avicii",
  "Avril Lavigne",
  "BORDERLVND",
  "BORNS",
  "BRUTTO",
  "Babyshambles",
  "Bad Religion",
  "Badda Boo Happy Band",
  "Balmorhea",
  "Balthazar",
  "Band of Horses",
  "Bang Gang",
  "Baptiste Giabiconi",
  "Barenaked Ladies",
  "Basil Poledouris",
  "Bastille",
  "Bat for Lashes",
  "Beach House",
  "Bear's Den",
  "Beck",
  "Belinda Carlisle",
  "Ben Harper",
  "Ben Woods",
  "Bibio",
  "Billy Idol",
  "Birdy",
  "Black Hill & Silent Island",
  "Black Stone Cherry",
  "Blonde Redhead",
  "Blur",
  "Bon Iver",
  "Bon Jovi",
  "Bowerbirds",
  "Boyce Avenue",
  "Brainstorm",
  "Brandon Flowers",
  "Brick + Mortar",
  "Bring Me The Horizon",
  "Broods",
  "Bryan Adams",
  "Bullet for My Valentine",
  "CHVRCHES",
  "Cage the Elephant",
  "Camille",
  "Capital Cities",
  "Carly Comando",
  "Carnival Youth",
  "Carolina Liar",
  "Carpenter Brut",
  "Carrion",
  "Cat Power",
  "Charlotte Gainsbourg",
  "Chernikovskaya Hata",
  "Chevelle",
  "Chris De Burgh",
  "Chris Garneau",
  "Chris Rea",
  "Christina Aguilera",
  "Cigarettes After Sex",
  "City and Colour",
  "Clannad",
  "CocoRosie",
  "Cocoon",
  "Coeur de Pirate",
  "Coldrain",
  "Columbia Mills",
  "Crystal Castles",
  "Crywank",
  "Daft Punk",
  "Damien Rice",
  "Danny Worsnop",
  "Darkhan Juzz",
  "David Bowie",
  "Dead Man's Bones",
  "Dead by April",
  "Dead by Sunrise",
  "Death Cab for Cutie",
  "Deftones",
  "Depeche Mode",
  "Digital Daggers",
  "Dillon",
  "Disciple",
  "Disturbed",
  "Doris Day",
  "DragonForce",
  "Dream Theater",
  "Duke Dumont",
  "Duran Duran",
  "Eels",
  "Egypt Central",
  "Electric Light Orchestra",
  "Electric Youth",
  "Elliott Smith",
  "Elvis Presley",
  "Emilie Autumn",
  "Eminem",
  "Empire of the Sun",
  "Enigma",
  "Ennio Morricone",
  "Enya",
  "Erasure",
  "Erik Satie",
  "Evanescence",
  "Explosions in the Sky",
  "Fabrizio Paterlini",
  "Fall Out Boy",
  "Fall Out Boys",
  "Feeder",
  "Fifth Harmony",
  "Fiona Apple",
  "First Aid Kit",
  "Fleet Foxes",
  "Flyleaf",
  "Foo Fighters",
  "Fools Garden",
  "Foster the People",
  "Fountains of Wayne",
  "Fraine",
  "Franz Ferdinand",
  "Franz Schubert",
  "Garbage",
  "Garden City Movement",
  "George Davidson",
  "George Harrison",
  "Gin Lady",
  "Gipsy Kings",
  "Glass Animals",
  "Glee Cast",
  "God Is an Astronaut",
  "Goldmund",
  "Good Charlote",
  "Good Charlotte",
  "Grand National",
  "Gregorian",
  "Gregory Alan Isakov",
  "Gulmira Issimbayeva",
  "Guns N' Roses",
  "Gustavo Santaolalla",
  "Gwen Stefani",
  "H.E.R.",
  "HONNE",
  "Halsey",
  "Hammock",
  "Handsome Ghost",
  "Hans Zimmer",
  "Haux",
  "Hiatus",
  "Hidden Citizens",
  "Holly Henry",
  "Hollywood Undead",
  "Hoobastank",
  "Hooverphonic",
  "Hospital",
  "Howie Day",
  "Hozier",
  "Hurt",
  "Hurts",
  "Husky Rescue",
  "Hypnogaja",
  "I Am Kloot",
  "I Am Waiting for You Last Summer",
  "IAMX",
  "INXS",
  "IVATU",
  "Ilya Beshevli",
  "In Flames",
  "In This Moment",
  "Incubus",
  "Ingrid Michaelson",
  "Interpol",
  "Iron & Wine",
  "Ison",
  "JJ",
  "Jack Garratt",
  "Jack Johnson",
  "Jake Bugg",
  "James Arthur",
  "James Bay",
  "James Blunt",
  "James Young",
  "Jamiroquai",
  "Jaymes Young",
  "Jazzamor",
  "Jeffrey Swann",
  "Jem",
  "Jeremy Soule",
  "Jet",
  "Joe Hisaishi",
  "Joel Goldsmith",
  "John Frusciante",
  "John Grant",
  "John Mayer",
  "John Williams",
  "Johnny Cash",
  "Joshua Radin",
  "Journey",
  "Kaiser Chiefs",
  "Kakkmaddafakka",
  "Kasabian",
  "Kate Nash",
  "Kate Rusby",
  "Katie Melua",
  "Katy Perry",
  "Keaton Henson",
  "Keira Knightley",
  "Kilo Kish",
  "Kings Of Leon",
  "Koop",
  "Krec",
  "Kutless",
  "LP",
  "La Femme",
  "Lacuna Coil",
  "Lady Pank",
  "Laura Marling",
  "Laurel",
  "Leonard Cohen",
  "Lera Lynn",
  "Lily Allen",
  "Limp Bizkit",
  "Linnea Olsson",
  "Lissie",
  "Logh",
  "Lola Marsh",
  "London Grammar",
  "Lorde",
  "Lostprophets",
  "Louna",
  "Low Roar",
  "Low",
  "Lucius",
  "Lucy Rose",
  "Lykke Li",
  "MGMT",
  "MIKA",
  "MS MR",
  "Mac DeMarco",
  "Magic Bronson",
  "Making April",
  "Manchester Orchestra",
  "Mando Diao",
  "Mansionair",
  "Marceline",
  "Maria Peszek",
  "Marilyn Manson",
  "Massive Attack",
  "Mat Kearney",
  "Matt Corby",
  "Max Richter",
  "Maybeshewill",
  "Mazzy Star",
  "McFly",
  "Melanie Martinez",
  "Metric",
  "Mexicolas",
  "Mgzavrebi",
  "Michael Jackson",
  "Middle Kids",
  "Midlake",
  "Mike Paer",
  "Mild Minds",
  "Miles Davis",
  "Miles Kane",
  "Milky Chance",
  "Moddi",
  "Modern Talking",
  "Mogwai",
  "Moldanazar",
  "Molto Loud",
  "Monogrenade",
  "Morcheeba",
  "Morrissey",
  "Motorama",
  "Mudvayne",
  "Mumford & Sons",
  "Mushmellow",
  "My Darkest Days",
  "Mylène Farmer",
  "MØ",
  "N.R.M.",
  "Naka",
  "Negative",
  "Neulore",
  "Never Shout Never",
  "New Politics",
  "Nils Frahm",
  "Nine Lashes",
  "Nirvana",
  "Nizkiz",
  "No Clear Mind",
  "Norah Jones",
  "Nothing More",
  "Nothing but Thieves",
  "Nouvelle Vague",
  "O.Torvald",
  "OQJAV",
  "Ocean Jet",
  "Of the Valley",
  "Old Man Canyon",
  "Other Lives",
  "Otto Dix",
  "Our Last Night",
  "Ourlives",
  "Ozzy Osbourne",
  "P.O.D.",
  "Panama",
  "Papa Roach",
  "Paramore",
  "Parks, Squares and Alleys",
  "Parov Stelar",
  "Passenger",
  "Patrick Wolf",
  "Paul Mauriat",
  "Paul McCartney",
  "Pearl Jam",
  "Peggy Lee",
  "Pete Murray",
  "Peter Broderick",
  "Petit Biscuit",
  "Phantom Planet",
  "Phil Collins",
  "Philip Glass",
  "Phum Viphurit",
  "Pillar",
  "Pink Floyd",
  "Pink",
  "Pompeya",
  "Porcupine Tree",
  "Portishead",
  "Portugal. The Man",
  "Princess Chelsea",
  "Puggy",
  "Puzzle Muteson",
  "RADIO TAPOK",
  "RHODES",
  "RSAC",
  "RY X",
  "Rachael Yamagata",
  "Radical Face",
  "Rammstein",
  "Ramones",
  "Razorlight",
  "Reamon",
  "Reamonn",
  "Redlight King",
  "Regina Spector",
  "Regina Spektor",
  "Rhye",
  "Ricky Martin",
  "Riley Pearce",
  "Rise Against",
  "Robbie Williams",
  "Roberto Cacciapaglia",
  "Robot Koch",
  "Ron Pope",
  "Roo Panes",
  "Roxette",
  "Roy Orbison",
  "Russian Red",
  "Ryan Star",
  "Rökkurró",
  "SOKO",
  "SYML",
  "Sabaton",
  "Sade",
  "Saint Asonia",
  "San Carol",
  "Savage Garden",
  "Scissor Sisters",
  "Scouting for Girls",
  "Sea Wolf",
  "Seabear",
  "Serj Tankian",
  "ShamRain",
  "Shelby Merry",
  "Sheryl Crow",
  "Shinedown",
  "Shout Out Louds",
  "Sia",
  "Sibylle Baier",
  "Sigrid",
  "Sigur Ros",
  "Sin Fang",
  "Skillet",
  "Sleeping at Last",
  "Slipknot",
  "Smash Mouth",
  "Smile Empty Soul",
  "Snakadaktal",
  "So Below",
  "Son Lux",
  "Sopor Aeternus & The Ensemble of Shadows",
  "Spector",
  "Spring King",
  "Staind",
  "Starsailor",
  "Starset",
  "Steady Holiday",
  "Stevie Wonder",
  "Stigmata",
  "Sting",
  "Story Of The Year",
  "Strung Out",
  "Sublime",
  "Submersed",
  "Sufjan Stevens",
  "Sunrise Avenue",
  "Swim Deep",
  "Switchfoot",
  "Syd Matters",
  "Syntax",
  "System of a Down",
  "Take That",
  "Talco",
  "Tamino",
  "Taylor Swift",
  "The 1975",
  "The 69 Eyes",
  "The All-American Rejects",
  "The Antlers",
  "The Beatles",
  "The Birthday Massacre",
  "The Calling",
  "The Chordettes",
  "The Civil Wars",
  "The Cure",
  "The Decemberists",
  "The Doors",
  "The Dø",
  "The Essex Green",
  "The Frames",
  "The Fratellis",
  "The Gaslight Anthem",
  "The Growlers",
  "The Handsome Family",
  "The Heavy",
  "The Kooks",
  "The Last Shadow Puppets",
  "The Maine",
  "The Mowgli's",
  "The New Pornographers",
  "The Notwist",
  "The Offspring",
  "The Oh Hello's",
  "The Paper Kites",
  "The Piano Guys",
  "The Pierces",
  "The Pretty Reckless",
  "The Rasmus",
  "The Retuses",
  "The Script",
  "The Smashing Pumpkins",
  "The Strokes",
  "The Vaccines",
  "The Veils",
  "The Velvet Underground",
  "The Verve",
  "The Vitamin String Quartet",
  "The War on Drugs",
  "The Weeknd",
  "The Wooden Sky",
  "The Wytches",
  "The Zolas",
  "Theatres des Vampires",
  "Theory of a Deadman",
  "Thirteen Senses",
  "Thirty Seconds to Mars",
  "This Will Destroy You",
  "Thom Yorke",
  "Thousand Foot Krutch",
  "Tim Minchin",
  "Tokio Hotel",
  "Tom Grennan",
  "Tom Odell",
  "Tom Rosenthal",
  "Tori Amos",
  "Torres",
  "Tracktor Bowling",
  "Troye Sivan",
  "Tunng",
  "Twenty One Pilots",
  "Two Door Cinema Club",
  "Two Feet",
  "Two Steps from Hell",
  "Tycho",
  "Tyrone Wells",
  "Uma2rman",
  "VAST",
  "Vance Joy",
  "Vancouver Sleep Clinic",
  "Vanessa May",
  "Vanilla Sky",
  "Voyager",
  "Vök",
  "WILDES",
  "Walk The Moon",
  "Warpaint",
  "Washed Out",
  "We The Kings",
  "Weezer",
  "Whitesnake",
  "Whitney Huston",
  "Wild Child",
  "William Control",
  "Wolf Alice",
  "Wolf Colony",
  "Woodkid",
  "Woolookologie",
  "Wrongonyou",
  "X Ambassadors",
  "Xandria",
  "Yann Tiersen",
  "Yeah Yeah Yeahs",
  "Yellowcard",
  "Yeong Wook Jo",
  "Yiruma",
  "Your Favorite Enemies",
  "Youth Group",
  "Youth Lagoon",
  "Yuna",
  "Zebrahead",
  "Zee Avi",
  "Zella Day",
  "Zero People",
  "Zola Blood",
  "[AMATORY]",
  "blink-182",
  "city&shivers",
  "daKooka",
  "iamamiwhoami",
  "ili-ili",
  "mtmrfz",
  "prvrln",
  "shura",
  "t.A.T.u.",
  "Árstíðir",
  "Čas Łajna",
  "Аквариум",
  "Алина Орлова",
  "Алиса",
  "Ария",
  "Баста",
  "Без Билета",
  "Белая Гвардия",
  "Биопсихоз",
  "Борис Гребенщиков",
  "Владимир Кузьмин",
  "Гражданская Оборона",
  "ДМЦ",
  "Дельфин",
  "ДетиДетей",
  "Евгений Гришковец",
  "Евгения Рыбакова",
  "Егор Летов",
  "Жорж Бизе",
  "Жуки",
  "Звери",
  "Иванушки International",
  "Игорь Тальков",
  "Иоганн Себастьян Бах",
  "Канцлер Ги",
  "Кино",
  "Кипелов",
  "Крематорий",
  "Круг Михаил",
  "Лада Дэнс",
  "Ленинград",
  "Луна",
  "Любэ",
  "Люмен",
  "МакSим",
  "Мара",
  "Мария Чайковская",
  "Маша Badda Boo",
  "Машина времени",
  "Монеточка",
  "Моцарт",
  "Мумий тролль",
  "Мураками",
  "Муслим Магомаев",
  "Мутнаевока",
  "Мы",
  "НАИВ",
  "Найк Борзов",
  "Натали",
  "Нервы",
  "Ногу свело!",
  "Один в Каное",
  "Олег Газманов",
  "Олег Митяев",
  "Отпетые мошенники",
  "Пелагея",
  "Петля Пристрастия",
  "Петр Ильич Чайковский",
  "Пилот",
  "Порнофильмы",
  "Руки Вверх!",
  "Сансара",
  "Северный Флот",
  "Скрябін",
  "Слот",
  "Сурганова и Оркестр",
  "Т9",
  "Тени Свободы",
  "Торба-на-Круче",
  "Шары",
  "Юта",
  'All Time Low',
  'Animal ДжаZ',
  'Arctic Monkeys',
  'Ben Howard',
  'Blue October',
  'Breaking Benjamin',
  'Brian Crain',
  'Cemetery of Scream',
  'Coldplay',
  'Daughter',
  'Ed Sheeran',
  'Editors',
  'Foals',
  'Frank Sinatra',
  'Gorillaz',
  'Green Day',
  'HIM',
  'Imagine Dragons',
  'Kalle Mattson',
  'Keane',
  'Kings of Convenience',
  'Kodaline',
  'Lifehouse',
  'Linkin Park',
  'Ludovico Einaudi',
  'Lumen',
  'M83',
  'Maroon 5',
  'Moby',
  'Muse',
  'My Chemical Romance',
  'Nightwish',
  'Noize MC',
  'Oasis',
  'Of Monsters and Men',
  'Oh Wonder',
  'Oomph!',
  'Panic! at the Disco',
  'Placebo',
  'Poets of the Fall',
  'Queen',
  'Radiohead',
  'Red',
  'Scorpions',
  'Seafret',
  'Seether',
  'Simple Plan',
  'Snow Patrol',
  'Stereophonics',
  'Stone Sour',
  'TENDER',
  'The Cranberries',
  'The Fray',
  'The Killers',
  'The Mountain Goats',
  'The National',
  'The Neighbourhood',
  'The Wombats',
  'The XX',
  'Three Days Grace',
  'U2',
  'VLNY',
  'WMD',
  'Within Temptation',
  'travis',
  'Агата Кристи',
  'Браво',
  'ВИА "Волга-Волга"',
  'Город 312',
  'Земфира',
  'Кукрыниксы',
  'Ляпис Трубецкой',
  'Макс Корж',
  'Мельница',
  'Наутилус Помпилиус',
  'Ночные Снайперы',
  'Пошлая Молли',
  'Свидание',
  'Сергей Бабкин',
  'Смысловые Галлюцинации',
  'Сплин',
  'Танцы Минус',
  'Чайф',
  'Чичерина',
  ["4 Апреля", "4-e Апреля", "4-е Апреля"],
  ["Angus & Julia Stone", "Angus and Julia Stone"],
  ["BANNERS", 'BANNΞRS'],
  ["Fleur", "Flëur", "Флёр"],
  ["J:МОРС", "J:mors", "J:MOPC"],
  ["L'Orchestra Cinématique", "L'Orchestra Cinematique"],
  ["Nickelback", "Nikelback"],
  ["OneRepublic", "One Republic"],
  ["Sin Fang, Sóley & Örvar Smárason", "Sin Fang, Sóley And Örvar Smárason"],
  ["The Banner", 'Banner'],
  ["Антитіла", "Антитела"],
  ["Республика Полина", "Рэспубліка Паліна"],
  ["Сергей Бабкин", "Сергей Бабкин (2013 - Сергевна)"],
  ['Amy Macdonald', "Amy McDonald"],
  ['Decades', 'Decades - Decades [2013]'],
  ['Florence + the Machine', 'Florence and the Machine'],
  ['Hans Zimmer', "Бетховен(Hans Zimmer)"],
  ['Lana Del Rey', "Lana Del Ray"],
  ['MoZart', 'гурт "moZart"'],
  ['R.E.M.', 'REM'],
  ['Red Hot Chili Peppers', "RHCP"],
  ['Sum 41', "Sum41"],
  ['alt-J', "Alt-J (∆)"],
  ['Би-2', "Би 2", "Би-2 и симфонический оркестр", "Би-2 и Диана Арбенина"],
  ['Валентин Стрыкало', "Стрыкало", "Юрий Каплан"],
  ['ДДТ', "DDT"],
  ['Король и Шут', "Король и Шут (КиШ)"],
  ['Михаил Шуфутинский', "Шуфутинский Михаил"],
  ['Океан Ельзи', "ОКЕАН ЭЛЬЗЫ", "Океан Эльзи"],
  ['Пётр Ильич Чайковский', "П.И.Чайковский"],
  ['Чиж & Co', "Чиж и Ко"],

  # Long Titles

  [
    'The Last Shadow Puppets',
    "The Last Shadow Puppets feat. Alex Turner, Miles Kane"
  ],
  [
    'Camille Saint-Saëns',
    "David Victor-Smith, Julia Freeman, Farnham Youth Choir"
  ],
  [
    "Richard Blair-Oliphant",
    "Richard Blair-Oliphant (Score Score When We Left Earth)"
  ],
  [
    'Пётр Ильич Чайковский',
    "Лондонский симфонический оркестр, дирижер Чарльз Герхардт"
  ],
  [
    "Vitamin String Quartet",
    "Vitamin String Quartet - The Tribute Of 30 Seconds To Mars"
  ],
  [
    "Ólafur Arnalds & Alice Sara Ott",
    "Ólafur Arnalds & Alice Sara Ott - The Chopin Project [2015]"
  ],
  [
    "Николай Караченцов, Анна Большова",
    "Николай Караченцов, Анна Большова (рок-опера Юнона и Авось)"
  ],
  [
    "Kirin J Callinan",
    "Kirin J Callinan feat. Alex Cameron, Molly Lewis, Jimmy Barnes"
  ],
  [
    "The Philadelphia Orchestra",
    "The Philadelphia Orchestra, Sergei Rachmaninoff, Leopold Stokowski"
  ],
  [
    "Claude Debussy",
    "Classical Study Music, Studying Music, Relaxing Music, Claude Debussy"
  ],
  [
    "Green Day and American Idiot Cast",
    "Green Day feat. Stark Sands, Chase Peacock, Joshua Henry, Ben Thompson",
    "Green Day feat. Theo Stockman, Michael Esper, Mary Faber, Alysha Umphress",
    "The American Idiot feat. John Gallagher Jr., Stark Sands, Theo Stockman & Company",
    "Green Day feat. Tony Vincent, Rebecca Naomi Jones, Mary Faber, The American Idiot Broadway Company",
    "Green Day feat. John Gallagher Jr., Stark Sands, Theo Stockman, The American Idiot Broadway Company",
    "Green Day feat. Tony Vincent, John Gallagher Jr., Theo Stockman, The American Idiot Broadway Company",
    "Green Day feat. John Gallagher Jr., Declan Bennett, Theo Stockman, Tony Vincent, The American Idiot Broadway Company",
  ],
  [
    "Edward Sharpe",
    "Home - Edward Sharpe and The Magnetic Zeros Acoustic Cover by Jorge & Alexa Narvaez"
  ],
  [
    "Академический Ансамбль Песни и Пляски Советской Армии",
    "Георгий Виноградов, Дважды Краснознамённый ордена Красной Звезды академический ансамбль песни и пляски Советской Армии имени Александра Александрова"
  ],
]
